name: CI
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: dotnet restore src

    - name: Build Project
      run: dotnet build src

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: dotnet restore src

    - name: Build Project
      run: dotnet build src

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: dotnet restore src

    - name: Build Project
      run: dotnet build src

